#!/bin/bash
# make-fake-history-events.sh

scriptName="$(readlink -f "$0")"
scriptDir=$(command dirname -- "${scriptName}")

die() {
    builtin echo "ERROR($(basename ${scriptName})): $*" >&2
    builtin exit 1
}

help() {
    cat <<-EOF
fake-history-events.sh  --start-date "\$(date -d "2017-12-01T13:30" +%s)"
     # Create 30 fake records starting Dec 1 2017, one per day
EOF
}

stub() {
   builtin echo "  <<< STUB[$*] >>> " >&2
}
main() {
    local numEvents=30
    local startDate=$(date -d "${numEvents} days ago" +%s)  #
    while [[ -n $1 ]]; do
        case $1 in
            -h|--help)
                help
                exit
                ;;
            --start-date)
                startDate="$2"
                shift
                ;;
            *)
                die "bad args: $*"
                ;;
        esac
        shift
    done
    curDate=${startDate}
    eventNum=0
    while (( eventNum < numEvents  )); do
        echo "#${curDate}"
        echo "Event ${eventNum} @${curDate}, generated by # make-fake-history-events"
        (( eventNum++ ))
        curDate=$(( $curDate + 86400 ))
    done
}

[[ -z ${sourceMe} ]] && {
    main "$@"
    builtin exit
}
command true
